// Expressions courantes attestées dans les manuels et guides de conversation tchétchènes
// (méthode LIMBA, Waynakh Online, guides de conversation courants).
window.NM_PHRASES = [
 {cat:"Salutations", ce:"Маршалла ду хьоьга", fr:"Bonjour / salut (à une personne)"},
 {cat:"Salutations", ce:"Маршалла ду шуьга", fr:"Bonjour (à plusieurs personnes)"},
 {cat:"Salutations", ce:"Ассалам ӏалайкум", fr:"Salam aleykoum (entre hommes)"},
 {cat:"Salutations", ce:"Ваӏалайкум ассалам", fr:"Réponse au salam"},
 {cat:"Salutations", ce:"Ӏуьйре дика йойла", fr:"Bonne matinée"},
 {cat:"Salutations", ce:"Де дика дойла", fr:"Bonne journée"},
 {cat:"Salutations", ce:"Суьйре дика йойла", fr:"Bonne soirée"},
 {cat:"Salutations", ce:"Буьйса декъал йойла", fr:"Bonne nuit"},
 {cat:"Salutations", ce:"Марша ӏойла", fr:"Au revoir (à celui qui reste)"},
 {cat:"Salutations", ce:"Марша гӏойла", fr:"Au revoir (à celui qui part)"},
 {cat:"Politesse", ce:"Баркалла", fr:"Merci"},
 {cat:"Politesse", ce:"Дела реза хийла", fr:"Merci (litt. « que Dieu te soit favorable »)"},
 {cat:"Politesse", ce:"Дела аьтто бойла", fr:"Que Dieu t'aide (souhait de réussite)"},
 {cat:"Base", ce:"ХӀаъ", fr:"Oui"},
 {cat:"Base", ce:"ХӀан-хӀа", fr:"Non"},
 {cat:"Base", ce:"Дика ду", fr:"C'est bien / d'accord"},
 {cat:"Conversation", ce:"Хьо муха ву?", fr:"Comment vas-tu ? (à un homme)"},
 {cat:"Conversation", ce:"Хьо муха ю?", fr:"Comment vas-tu ? (à une femme)"},
 {cat:"Conversation", ce:"Со дика ву", fr:"Je vais bien (homme qui parle)"},
 {cat:"Conversation", ce:"Со дика ю", fr:"Je vais bien (femme qui parle)"},
 {cat:"Conversation", ce:"Хьан цӏе хӏун ю?", fr:"Comment t'appelles-tu ?"},
 {cat:"Conversation", ce:"Сан цӏе … ю", fr:"Je m'appelle …"},
 {cat:"Conversation", ce:"Хьо мичара ву?", fr:"D'où viens-tu ? (à un homme)"},
 {cat:"Conversation", ce:"Хьо мичара ю?", fr:"D'où viens-tu ? (à une femme)"},
 {cat:"Conversation", ce:"ХӀара хӀун ю?", fr:"Qu'est-ce que c'est ?"},
 {cat:"Langue", ce:"Суна нохчийн мотт ца хаьа", fr:"Je ne parle pas (ne connais pas) le tchétchène"},
 {cat:"Langue", ce:"Ас нохчийн мотт ӏамабо", fr:"J'apprends le tchétchène"},
 {cat:"Langue", ce:"Суна ца хаьа", fr:"Je ne sais pas"},
 {cat:"Sentiments", ce:"Суна хьо веза", fr:"Je t'aime (dit à un homme)"},
 {cat:"Sentiments", ce:"Суна хьо еза", fr:"Je t'aime (dit à une femme)"}
];
